server:
  port: 8088
  servlet:
    context-path: /ailab-manager


spring:
  application:
    name: ailab-manager

  #jdbc
  datasource:
    name: test
    url: jdbc:mysql://172.16.2.100:30090/ailab?useUnicode=true&characterEncoding=UTF-8
    username: ailab
    password: R0otAI1ab
###### \u4f7f\u7528druid\u6570\u636e\u6e90 ############
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  druid:
    interceptor: true

  #\u5206\u9875\u63d2\u4ef6
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
logging:
  #config: classpath:logback-${spring.profiles.active}.xml
  config: classpath:log/logback.xml  
